### ISSUE TITLE
Inquiry About Polynomial Modification in Boneh-Durfee Implementation

### ISSUE THREAD

**Issue by windyLiu0314** [mimoo/RSA-and-LLL-attacks#3]

**Comment by KXAND** [comment]
可能我没有理解你的意思，而且我只是本科生，不过： 

Boneh-Durfee 攻击的原理中模的不是e吗？而且phiN应该是未知的？所以对于式子k（A+s） == 1 mod e来说，你的式子只是等价于将k替换成k+e，二者同余？

**Comment by windyLiu0314** [comment]
感谢你的回复，我已经解决了这个问题，十分感谢你的帮助！

**Comment by windyLiu0314** [comment]
感谢你的帮助，方便再询问一下，目前更高效的BKZ算法是否能提高BD攻击的0.292界限呢？



在 2024-05-25 00:26:13，"Quicsand" ***@***.***> 写道：

可能我没有理解你的意思，而且我只是本科生，不过：

Boneh-Durfee 攻击的原理中模的不是e吗？而且phiN应该是未知的？所以对于式子k（A+s） == 1 mod e来说，你的式子只是等价于将k替换成k+e，二者同余？

**Comment by KXAND** [comment]
如前所述，我是本科生，所以我的了解是相当有限的（此前我甚至没有听过BKZ算法😂），所以也许并不能给你一个真正正确的答案。

不过我尝试尽量帮助你😂，所以我简单地进行了一些搜索：

2021年Stephen D. Miller等人有一篇文章名为*Coppersmith’s lattices and “focus groups”: an attack on small-exponent RSA*。这篇文章也引用了这个仓库。第三页提出的问题表明BD攻击仍然是目前最好的结果。第7页的例子可能表明你提到的BKZ算法无法提高BD攻击的界限。也许这篇文章能给你一些启发？

**Comment by windyLiu0314** [comment]
David你好，感谢你的回复，我认真阅读了你提到的那篇论文，希望你也允许我在我的论文中引用你的研究成果。

正如你所说，更换格基约简算法并不能提高BD攻击的界限，在LLL算法约束下的BD攻击，攻击成功条件是 N^{0.292 - \epsilon}，更换BKZ算法，只能做到减小epsilon。

不过我现在遇到一个问题，问题详细信息如下：
N=0xf4c548636db62ffcc7ac4a0797952bea9a65bd426175af2435f72657e67ec8194667bfa94ce23c6f1e5baf3201867ab41701f6b8768e71009c41a3d5e9e7c109455341d549c7611f9f52851a2f017906aa9ccbedb95d238468e2c8577d30ecc4f158e3811fd5e2a6051443d468e3506bbc39bba710e34a604ac9e85d0feef8b3; (1024 bits)

e=0x16f4b438ba14e05afa944f7da9904f8c78ea52e4ca0be7fa2b5f84e22ddd7b0578a3477b19b7bb4a7f825acc45da2dd10e62dbd94a3386b97d92ee817b0c66c1507514a7860b9139bc2ac3a4e0fe304199214da00a4ca82bfcb7b18253e7e6144828e584dac2dfb9a03fabaf2376ce7c269923fbb60fc68325b9f6443e1f896f; (1021 bits)

c=0x26b1823cf836b226e2f5c90fdcd8420dbfcd02765b26e52ef3e5c0ab494c2f4650e475e280b0b5fff0d5016621186420b09e4706a5866e4a3319f23ef09d92c4e36acba39a0f6213fbe5ee1a736ce383e6e12351e6cbfd43f10a96b7fe34bdbaf948f2fb075d9063723c9f747fe6247ae9209e5d417faf2e37e6fee2eb863556;

Known information: The private key d is within the range [2^299,2^300]

我试过很多方法，最后构建的格基维度都很大，而且得不到一个很好的结果，不知道你是否有一些想法呢？

感谢你的帮助，希望你能允许我在论文中引用你的研究成果。



在 2024-06-09 17:23:18，"Quicsand" ***@***.***> 写道：

如前所述，我是本科生，所以我的了解是相当有限的（此前我甚至没有听过BKZ算法😂），所以也许并不能给你一个真正正确的答案。

不过我尝试尽量帮助你😂，所以我简单地进行了一些搜索：

2021年Stephen D. Miller等人有一篇文章名为Coppersmith’s lattices and “focus groups”: an attack on small-exponent RSA。这篇文章也引用了这个仓库。第三页提出的问题表明BD攻击仍然是目前最好的结果。第7页的例子可能表明你提到的BKZ算法无法提高BD攻击的界限。也许这篇文章能给你一些启发？

**Comment by D33BaT0** [comment]
Isn't that a challenge in the competition that's going on right now? Is it reasonable to ask this?

> David你好，感谢你的回复，我认真阅读了你提到的那篇论文，希望你也允许我在我的论文中引用你的研究成果。 正如你所说，更换格基约简算法并不能提高BD攻击的界限，在LLL算法约束下的BD攻击，攻击成功条件是 N^{0.292 - \epsilon}，更换BKZ算法，只能做到减小epsilon。 不过我现在遇到一个问题，问题详细信息如下： N=0xf4c548636db62ffcc7ac4a0797952bea9a65bd426175af2435f72657e67ec8194667bfa94ce23c6f1e5baf3201867ab41701f6b8768e71009c41a3d5e9e7c109455341d549c7611f9f52851a2f017906aa9ccbedb95d238468e2c8577d30ecc4f158e3811fd5e2a6051443d468e3506bbc39bba710e34a604ac9e85d0feef8b3; (1024 bits) e=0x16f4b438ba14e05afa944f7da9904f8c78ea52e4ca0be7fa2b5f84e22ddd7b0578a3477b19b7bb4a7f825acc45da2dd10e62dbd94a3386b97d92ee817b0c66c1507514a7860b9139bc2ac3a4e0fe304199214da00a4ca82bfcb7b18253e7e6144828e584dac2dfb9a03fabaf2376ce7c269923fbb60fc68325b9f6443e1f896f; (1021 bits) c=0x26b1823cf836b226e2f5c90fdcd8420dbfcd02765b26e52ef3e5c0ab494c2f4650e475e280b0b5fff0d5016621186420b09e4706a5866e4a3319f23ef09d92c4e36acba39a0f6213fbe5ee1a736ce383e6e12351e6cbfd43f10a96b7fe34bdbaf948f2fb075d9063723c9f747fe6247ae9209e5d417faf2e37e6fee2eb863556; Known information: The private key d is within the range [2^299,2^300] 我试过很多方法，最后构建的格基维度都很大，而且得不到一个很好的结果，不知道你是否有一些想法呢？ 感谢你的帮助，希望你能允许我在论文中引用你的研究成果。 在 2024-06-09 17:23:18，"Quicsand" ***@***.***> 写道： 如前所述，我是本科生，所以我的了解是相当有限的（此前我甚至没有听过BKZ算法😂），所以也许并不能给你一个真正正确的答案。 不过我尝试尽量帮助你😂，所以我简单地进行了一些搜索： 2021年Stephen D. Miller等人有一篇文章名为Coppersmith’s lattices and “focus groups”: an attack on small-exponent RSA。这篇文章也引用了这个仓库。第三页提出的问题表明BD攻击仍然是目前最好的结果。第7页的例子可能表明你提到的BKZ算法无法提高BD攻击的界限。也许这篇文章能给你一些启发？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by KXAND** [comment]
hello windy，
首先我希望你有注意到我不是David :-(
其次如果你已经解决了问题，那么最好是关闭这个issues，而不是删除你的提问信息，这可能会让后面看到的人感到困惑。

**Comment by Yhcyhcyhcyhcyhcyhc** [comment]
> Isn't that a challenge in the competition that's going on right now? Is it reasonable to ask this?
> 
> > David你好，感谢你的回复，我认真阅读了你提到的那篇论文，希望你也允许我在我的论文中引用你的研究成果。 正如你所说，更换格基约简算法并不能提高BD攻击的界限，在LLL算法约束下的BD攻击，攻击成功条件是 N^{0.292 - \epsilon}，更换BKZ算法，只能做到减小epsilon。 不过我现在遇到一个问题，问题详细信息如下： N=0xf4c548636db62ffcc7ac4a0797952bea9a65bd426175af2435f72657e67ec8194667bfa94ce23c6f1e5baf3201867ab41701f6b8768e71009c41a3d5e9e7c109455341d549c7611f9f52851a2f017906aa9ccbedb95d238468e2c8577d30ecc4f158e3811fd5e2a6051443d468e3506bbc39bba710e34a604ac9e85d0feef8b3; (1024 bits) e=0x16f4b438ba14e05afa944f7da9904f8c78ea52e4ca0be7fa2b5f84e22ddd7b0578a3477b19b7bb4a7f825acc45da2dd10e62dbd94a3386b97d92ee817b0c66c1507514a7860b9139bc2ac3a4e0fe304199214da00a4ca82bfcb7b18253e7e6144828e584dac2dfb9a03fabaf2376ce7c269923fbb60fc68325b9f6443e1f896f; (1021 bits) c=0x26b1823cf836b226e2f5c90fdcd8420dbfcd02765b26e52ef3e5c0ab494c2f4650e475e280b0b5fff0d5016621186420b09e4706a5866e4a3319f23ef09d92c4e36acba39a0f6213fbe5ee1a736ce383e6e12351e6cbfd43f10a96b7fe34bdbaf948f2fb075d9063723c9f747fe6247ae9209e5d417faf2e37e6fee2eb863556; Known information: The private key d is within the range [2^299,2^300] 我试过很多方法，最后构建的格基维度都很大，而且得不到一个很好的结果，不知道你是否有一些想法呢？ 感谢你的帮助，希望你能允许我在论文中引用你的研究成果。 在 2024-06-09 17:23:18，"Quicsand" _**@**_._**> 写道： 如前所述，我是本科生，所以我的了解是相当有限的（此前我甚至没有听过BKZ算法😂），所以也许并不能给你一个真正正确的答案。 不过我尝试尽量帮助你😂，所以我简单地进行了一些搜索： 2021年Stephen D. Miller等人有一篇文章名为Coppersmith’s lattices and “focus groups”: an attack on small-exponent RSA。这篇文章也引用了这个仓库。第三页提出的问题表明BD攻击仍然是目前最好的结果。第7页的例子可能表明你提到的BKZ算法无法提高BD攻击的界限。也许这篇文章能给你一些启发？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.**_>

麻烦问一下，你有解决这个问题吗

**Comment by windyLiu0314** [comment]
没  这个难度太大了  没找到符合的论文

---- Replied Message ----
| From | ***@***.***> |
| Date | 06/14/2024 22:28 |
| To | mimoo/RSA-and-LLL-attacks ***@***.***> |
| Cc | windyLiu0314 ***@***.***>,
State ***@***.***> |
| Subject | Re: [mimoo/RSA-and-LLL-attacks] Inquiry About Polynomial Modification in Boneh-Durfee Implementation (Issue #3) |

Isn't that a challenge in the competition that's going on right now? Is it reasonable to ask this?

David你好，感谢你的回复，我认真阅读了你提到的那篇论文，希望你也允许我在我的论文中引用你的研究成果。 正如你所说，更换格基约简算法并不能提高BD攻击的界限，在LLL算法约束下的BD攻击，攻击成功条件是 N^{0.292 - \epsilon}，更换BKZ算法，只能做到减小epsilon。 不过我现在遇到一个问题，问题详细信息如下： N=0xf4c548636db62ffcc7ac4a0797952bea9a65bd426175af2435f72657e67ec8194667bfa94ce23c6f1e5baf3201867ab41701f6b8768e71009c41a3d5e9e7c109455341d549c7611f9f52851a2f017906aa9ccbedb95d238468e2c8577d30ecc4f158e3811fd5e2a6051443d468e3506bbc39bba710e34a604ac9e85d0feef8b3; (1024 bits) e=0x16f4b438ba14e05afa944f7da9904f8c78ea52e4ca0be7fa2b5f84e22ddd7b0578a3477b19b7bb4a7f825acc45da2dd10e62dbd94a3386b97d92ee817b0c66c1507514a7860b9139bc2ac3a4e0fe304199214da00a4ca82bfcb7b18253e7e6144828e584dac2dfb9a03fabaf2376ce7c269923fbb60fc68325b9f6443e1f896f; (1021 bits) c=0x26b1823cf836b226e2f5c90fdcd8420dbfcd02765b26e52ef3e5c0ab494c2f4650e475e280b0b5fff0d5016621186420b09e4706a5866e4a3319f23ef09d92c4e36acba39a0f6213fbe5ee1a736ce383e6e12351e6cbfd43f10a96b7fe34bdbaf948f2fb075d9063723c9f747fe6247ae9209e5d417faf2e37e6fee2eb863556; Known information: The private key d is within the range [2^299,2^300] 我试过很多方法，最后构建的格基维度都很大，而且得不到一个很好的结果，不知道你是否有一些想法呢？ 感谢你的帮助，希望你能允许我在论文中引用你的研究成果。 在 2024-06-09 17:23:18，"Quicsand" @.> 写道： 如前所述，我是本科生，所以我的了解是相当有限的（此前我甚至没有听过BKZ算法😂），所以也许并不能给你一个真正正确的答案。 不过我尝试尽量帮助你😂，所以我简单地进行了一些搜索： 2021年Stephen D. Miller等人有一篇文章名为Coppersmith’s lattices and “focus groups”: an attack on small-exponent RSA。这篇文章也引用了这个仓库。第三页提出的问题表明BD攻击仍然是目前最好的结果。第7页的例子可能表明你提到的BKZ算法无法提高BD攻击的界限。也许这篇文章能给你一些启发？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _@**.**_>

麻烦问一下，你有解决这个问题吗

**Comment by mimoo** [comment]
对不起我不能帮助，我的中文太差
